# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - test031

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_6fbe6c134c0e4598ba77fade60bbb2e9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c6ad979bcc684c2f91127593954496e4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6fbe6c134c0e4598ba77fade60bbb2e9 }}/test2:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'test031'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_be45bc13dd344fe4bb8f6e70259c7280 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6fbe6c134c0e4598ba77fade60bbb2e9 }}/test2:${{ github.sha }}'